apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-7cmn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-7cmn
    app.kubernetes.io/part-of: tkrw-pr714-0075-0047-app
  name: devfile-sample-7cmn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-7cmn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-7cmn
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0047-tenant/tkrw-pr714-0075-0047-app/devfile-sample-7cmn@sha256:2fbb416e09e8d4be451a3fd2f94f7d206138d80eb635f14618391ae5f3508f71
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
